# Generated by Django 5.2 on 2025-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image_link', models.URLField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monthmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='monthmodel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='months', to='api.productmodel'),
        ),
    ]
