# Generated by Django 5.2 on 2025-04-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productmodel_alter_monthmodel_id_monthmodel_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
